using Awana.Data.Entities;

namespace Awana.Api.Contracts;

// --------------------------------------------------------------- scoreboard

/// <summary>
/// Everything a board or console needs to render, in one payload.
/// </summary>
/// <param name="Version">
/// The session's logical clock. After a reconnect a queued real-time message
/// can arrive later than a fresher refetch, so clients keep the highest version
/// they have seen and discard anything older. Two lines of client code that
/// remove a whole class of "the board jumped back" bug.
/// </param>
/// <param name="ServerTimeUtc">
/// Lets the board show "updated 4s ago" against the server's clock rather than
/// the viewer's, which on a shared TV is frequently wrong.
/// </param>
public sealed record ScoreboardDto(
    Guid SessionId,
    string Slug,
    string DivisionName,
    DateOnly Date,
    SessionStatus Status,
    int Version,
    int RoundCount,
    IReadOnlyList<StandingDto> Standings,
    LastRoundDto? LastRound,
    DateTimeOffset ServerTimeUtc);

public sealed record StandingDto(
    Guid TeamId,
    string Name,
    string ColorHex,
    string TextOnColorHex,
    decimal Points,
    int Rank,
    int RankChange,
    IReadOnlyDictionary<int, int> PlaceCounts);

public sealed record LastRoundDto(
    Guid RoundId,
    int RoundNumber,
    string GameName,
    decimal Multiplier,
    IReadOnlyList<RoundTeamDto> Teams);

public sealed record RoundTeamDto(
    Guid TeamId,
    string TeamName,
    int? Place,
    bool IsDisqualified,
    decimal Points,
    decimal BonusPoints,
    string Explanation);

// ------------------------------------------------------------------ rounds

/// <param name="ClientRequestId">
/// One value per round ATTEMPT, generated by the client and reused on retry.
/// A retry after a lost response returns the existing round instead of scoring
/// it a second time.
/// </param>
public sealed record CreateRoundRequest(
    Guid ClientRequestId,
    Guid GameId,
    decimal Multiplier,
    IReadOnlyList<RoundEntryRequest> Entries);

public sealed record UpdateRoundRequest(
    Guid GameId,
    decimal Multiplier,
    IReadOnlyList<RoundEntryRequest> Entries);

/// <param name="Place">Tied teams share a value. Null means the team did not take part.</param>
public sealed record RoundEntryRequest(
    Guid TeamId,
    int? Place,
    bool IsDisqualified,
    decimal Bonus,
    string? BonusReason);

public sealed record VoidRoundRequest(string Reason);

/// <summary>
/// The response to recording a round: the round, what each team earned, and the
/// whole scoreboard.
///
/// The scoreboard rides along so the console needs no second round trip and
/// cannot end up showing something different from the TV.
/// </summary>
public sealed record RoundRecordedDto(
    Guid RoundId,
    int RoundNumber,
    IReadOnlyList<RoundTeamDto> Awards,
    ScoreboardDto Scoreboard);

// ----------------------------------------------------------------- preview

public sealed record PreviewRequest(
    Guid GameId,
    decimal Multiplier,
    IReadOnlyList<RoundEntryRequest> Entries);

/// <summary>
/// What a round WOULD score, with nothing written.
///
/// This is what makes the console's live panel honest: the scorekeeper confirms
/// points computed by the same engine that will store them, not a second
/// implementation in the browser that can drift.
/// </summary>
public sealed record PreviewDto(
    bool IsValid,
    IReadOnlyList<ValidationErrorDto> Errors,
    IReadOnlyList<RoundTeamDto> Awards);

public sealed record ValidationErrorDto(string Code, string Message);

// ---------------------------------------------------------------- sessions

public sealed record SessionSummaryDto(
    Guid Id,
    string Slug,
    string DivisionName,
    DateOnly Date,
    SessionStatus Status,
    int RoundCount);

public sealed record CreateSessionRequest(Guid DivisionId, DateOnly Date);

public sealed record SessionDetailDto(
    Guid Id,
    string Slug,
    Guid DivisionId,
    string DivisionName,
    DateOnly Date,
    SessionStatus Status,
    int Version,
    IReadOnlyList<SessionTeamDto> Teams,
    IReadOnlyList<RoundSummaryDto> Rounds,
    IReadOnlyList<AdjustmentDto> Adjustments);

public sealed record SessionTeamDto(
    Guid TeamId,
    string Name,
    string ColorHex,
    string TextOnColorHex,
    int? Headcount);

public sealed record RoundSummaryDto(
    Guid Id,
    int RoundNumber,
    Guid GameId,
    string GameName,
    decimal Multiplier,
    bool IsVoided,
    string? VoidReason,
    IReadOnlyList<RoundTeamDto> Teams);

public sealed record GameDto(Guid Id, string Name, bool IsCore, Guid? DivisionId);

/// <summary>
/// Points a leader decided on, outside the games.
///
/// Separate from a round result on purpose, so that "what happened in the
/// games" and "what a leader decided" stay distinguishable when somebody asks
/// how a total was arrived at.
/// </summary>
public sealed record AdjustmentDto(
    Guid Id,
    Guid TeamId,
    string TeamName,
    decimal Points,
    string Reason,
    bool IsVoided,
    DateTimeOffset CreatedAt);

/// <summary>Points may be negative: a penalty is an adjustment too.</summary>
public sealed record CreateAdjustmentRequest(
    Guid TeamId,
    decimal Points,
    string Reason);

/// <summary>Headcounts, all of them at once. Null clears one.</summary>
public sealed record UpdateAttendanceRequest(
    IReadOnlyList<TeamHeadcount> Teams);

public sealed record TeamHeadcount(Guid TeamId, int? Headcount);

/// <summary>
/// Who the caller is, or that they are nobody.
///
/// Anonymous is an ordinary answer rather than a 401, because the web app asks
/// this before it knows which page it is allowed to show.
/// </summary>
public sealed record MeDto(
    bool IsSignedIn,
    Guid? UserId,
    string? DisplayName,
    string? Role);
