using Awana.Data.Entities;
using Awana.Scoring;

namespace Awana.Api.Contracts;

// --------------------------------------------------------------- scoreboard

/// <summary>
/// Everything a board or console needs to render, in one payload.
/// </summary>
/// <param name="Version">
/// The session's logical clock. After a reconnect a queued real-time message
/// can arrive later than a fresher refetch, so clients keep the highest version
/// they have seen and discard anything older. Two lines of client code that
/// remove a whole class of "the board jumped back" bug.
/// </param>
/// <param name="ServerTimeUtc">
/// Lets the board show "updated 4s ago" against the server's clock rather than
/// the viewer's, which on a shared TV is frequently wrong.
/// </param>
public sealed record ScoreboardDto(
    Guid SessionId,
    string Slug,
    string DivisionName,
    DateOnly Date,
    SessionStatus Status,
    int Version,
    int RoundCount,
    IReadOnlyList<StandingDto> Standings,
    LastRoundDto? LastRound,
    DateTimeOffset ServerTimeUtc);

public sealed record StandingDto(
    Guid TeamId,
    string Name,
    string ColorHex,
    string TextOnColorHex,
    decimal Points,
    int Rank,
    int RankChange,
    IReadOnlyDictionary<int, int> PlaceCounts);

public sealed record LastRoundDto(
    Guid RoundId,
    int RoundNumber,
    string GameName,
    decimal Multiplier,
    IReadOnlyList<RoundTeamDto> Teams);

public sealed record RoundTeamDto(
    Guid TeamId,
    string TeamName,
    int? Place,
    bool IsDisqualified,
    decimal Points,
    decimal BonusPoints,
    string Explanation);

// ------------------------------------------------------------------ rounds

/// <param name="ClientRequestId">
/// One value per round ATTEMPT, generated by the client and reused on retry.
/// A retry after a lost response returns the existing round instead of scoring
/// it a second time.
/// </param>
public sealed record CreateRoundRequest(
    Guid ClientRequestId,
    Guid GameId,
    decimal Multiplier,
    IReadOnlyList<RoundEntryRequest> Entries);

public sealed record UpdateRoundRequest(
    Guid GameId,
    decimal Multiplier,
    IReadOnlyList<RoundEntryRequest> Entries);

/// <param name="Place">Tied teams share a value. Null means the team did not take part.</param>
public sealed record RoundEntryRequest(
    Guid TeamId,
    int? Place,
    bool IsDisqualified,
    decimal Bonus,
    string? BonusReason);

public sealed record VoidRoundRequest(string Reason);

/// <summary>
/// The response to recording a round: the round, what each team earned, and the
/// whole scoreboard.
///
/// The scoreboard rides along so the console needs no second round trip and
/// cannot end up showing something different from the TV.
/// </summary>
public sealed record RoundRecordedDto(
    Guid RoundId,
    int RoundNumber,
    IReadOnlyList<RoundTeamDto> Awards,
    ScoreboardDto Scoreboard);

// ----------------------------------------------------------------- preview

public sealed record PreviewRequest(
    Guid GameId,
    decimal Multiplier,
    IReadOnlyList<RoundEntryRequest> Entries);

/// <summary>
/// What a round WOULD score, with nothing written.
///
/// This is what makes the console's live panel honest: the scorekeeper confirms
/// points computed by the same engine that will store them, not a second
/// implementation in the browser that can drift.
/// </summary>
public sealed record PreviewDto(
    bool IsValid,
    IReadOnlyList<ValidationErrorDto> Errors,
    IReadOnlyList<RoundTeamDto> Awards);

public sealed record ValidationErrorDto(string Code, string Message);

// ---------------------------------------------------------------- sessions

public sealed record SessionSummaryDto(
    Guid Id,
    string Slug,
    string DivisionName,
    DateOnly Date,
    SessionStatus Status,
    int RoundCount);

/// <param name="ScoringProfileId">
/// Which set of rules this night runs under. Null takes the church's default,
/// which is what almost every session wants.
/// </param>
public sealed record CreateSessionRequest(
    Guid DivisionId,
    DateOnly Date,
    Guid? ScoringProfileId = null);

public sealed record SessionDetailDto(
    Guid Id,
    string Slug,
    Guid DivisionId,
    string DivisionName,
    DateOnly Date,
    SessionStatus Status,
    int Version,
    SessionScoringDto Scoring,
    IReadOnlyList<SessionTeamDto> Teams,
    IReadOnlyList<RoundSummaryDto> Rounds,
    IReadOnlyList<AdjustmentDto> Adjustments);

/// <summary>
/// Which rules this session scores under, said out loud.
/// </summary>
/// <remarks>
/// Worth showing even when the church has only one set and there was never a
/// choice to make: a scorekeeper looking at a total should be able to see what
/// produced it without leaving the screen.
/// </remarks>
/// <param name="IsFixed">
/// True once the session has started and the rules are frozen onto it. Until
/// then this is what it WOULD use, which is not the same promise.
/// </param>
/// <param name="IsDefault">
/// True when nobody chose and this is simply the church's default. Before the
/// session starts that means it can still change under it, if the default moves.
/// </param>
/// <param name="ScoringProfileId">Null puts it back on the church's default.</param>
public sealed record SetSessionScoringRequest(Guid? ScoringProfileId);

public sealed record SessionScoringDto(
    string Name,
    IReadOnlyList<decimal> PlacePoints,
    bool IsFixed,
    bool IsDefault);

public sealed record SessionTeamDto(
    Guid TeamId,
    string Name,
    string ColorHex,
    string TextOnColorHex,
    int? Headcount);

public sealed record RoundSummaryDto(
    Guid Id,
    int RoundNumber,
    Guid GameId,
    string GameName,
    decimal Multiplier,
    bool IsVoided,
    string? VoidReason,
    IReadOnlyList<RoundTeamDto> Teams);

/// <summary>What the round picker needs, and nothing else.</summary>
public sealed record GameDto(Guid Id, string Name);

/// <summary>
/// A game as the catalog shows it, retired ones included.
/// </summary>
/// <param name="RoundCount">
/// A gate, not a statistic. Zero means the game can be deleted outright;
/// anything else means retiring is the only honest option, because rounds point
/// at it. The catalog does not show this number and should not start: how often
/// a game gets played is week to week tracking, which is its own screen.
/// </param>
/// <param name="IsSeeded">
/// True for a game the seeder created. Shown so that a leader editing the
/// catalog can tell which entries came with the app, and nothing more: a
/// seeded game is edited, retired and renamed exactly like any other.
/// </param>
public sealed record GameDetailDto(
    Guid Id,
    string Name,
    string? Notes,
    int SortOrder,
    bool IsActive,
    int RoundCount,
    bool IsSeeded);

/// <summary>
/// The editable half of a game. Used for both create and update, because the
/// form is the same one either way and two near-identical records would drift.
/// </summary>
public sealed record SaveGameRequest(
    string Name,
    string? Notes);

/// <summary>
/// The whole catalog's order, as ids in the order they should appear.
/// </summary>
/// <remarks>
/// Sent whole rather than as a move, so the result cannot depend on what the
/// server thought the order was. Two leaders reordering at once then means the
/// second one wins, rather than the two interleaving into something neither
/// asked for.
/// </remarks>
public sealed record ReorderGamesRequest(IReadOnlyList<Guid> Ids);

// -------------------------------------------------------------- scoring rules

/// <summary>
/// A named set of scoring rules, as the admin screen shows it.
/// </summary>
/// <param name="Config">
/// The rules themselves, in exactly the shape the engine consumes. Not
/// remodelled into a parallel DTO: there is one definition of what a scoring
/// rule is, and a second one would drift from the engine that executes it.
/// </param>
/// <param name="SessionCount">
/// How many sessions were started from these rules. A gate rather than a
/// statistic: zero is what makes a profile deletable, because a session that
/// used it would otherwise lose the record of where its scoring came from.
/// </param>
/// <param name="IsSeeded">
/// Came with the app, and is therefore read only even to an admin. Duplicating
/// it is how a church gets a set it can change. See ScoringProfile.SeedKey.
/// </param>
public sealed record ScoringProfileDto(
    Guid Id,
    string Name,
    ScoringConfig Config,
    bool IsDefault,
    bool IsActive,
    int SessionCount,
    bool IsSeeded);

public sealed record SaveScoringProfileRequest(string Name, ScoringConfig Config);

/// <summary>
/// What a set of rules would do, worked through on four rounds.
/// </summary>
/// <remarks>
/// Computed by the real engine on the server rather than in the browser. The
/// whole point is that the editor shows what Friday will actually do, which a
/// second implementation would eventually stop doing.
/// </remarks>
public sealed record ScoringPreviewDto(IReadOnlyList<ScoringExampleDto> Examples);

/// <param name="Rejected">
/// Set when the rules refuse this shape rather than scoring it, which is what
/// "ties are not allowed" looks like. Not an error: it is the clearest possible
/// demonstration of that setting.
/// </param>
public sealed record ScoringExampleDto(
    string Title,
    string Question,
    IReadOnlyList<ScoringExampleTeamDto> Teams,
    string? Rejected);

public sealed record ScoringExampleTeamDto(
    string TeamName,
    int? Place,
    bool IsDisqualified,
    decimal Points,
    string Explanation);

/// <summary>
/// Points a leader decided on, outside the games.
///
/// Separate from a round result on purpose, so that "what happened in the
/// games" and "what a leader decided" stay distinguishable when somebody asks
/// how a total was arrived at.
/// </summary>
public sealed record AdjustmentDto(
    Guid Id,
    Guid TeamId,
    string TeamName,
    decimal Points,
    string Reason,
    bool IsVoided,
    DateTimeOffset CreatedAt);

/// <summary>Points may be negative: a penalty is an adjustment too.</summary>
public sealed record CreateAdjustmentRequest(
    Guid TeamId,
    decimal Points,
    string Reason);

/// <summary>Headcounts, all of them at once. Null clears one.</summary>
public sealed record UpdateAttendanceRequest(
    IReadOnlyList<TeamHeadcount> Teams);

public sealed record TeamHeadcount(Guid TeamId, int? Headcount);

/// <summary>
/// Who the caller is, or that they are nobody.
///
/// Anonymous is an ordinary answer rather than a 401, because the web app asks
/// this before it knows which page it is allowed to show.
/// </summary>
public sealed record MeDto(
    bool IsSignedIn,
    Guid? UserId,
    string? DisplayName,
    /// <summary>
    /// Which account, as opposed to which person. Two volunteers can share a
    /// first name, and a shared laptop is the normal case, so the address is
    /// what actually answers "am I signed in as me".
    /// </summary>
    string? Email,
    string? Role);

// ---------------------------------------------------------------- people

/// <summary>
/// One account, as the People page shows it. Admins only: this is the one
/// payload in the API that lists other people's email addresses.
/// </summary>
/// <param name="Role">The role's name, the same spelling <see cref="MeDto"/> uses.</param>
/// <param name="HasSignedIn">
/// False for an address that was added but has never been used. Worth showing,
/// because it usually means a typo or somebody still waiting to be told.
/// </param>
/// <param name="IsConfigAdmin">
/// Listed in Seed__AdminEmails. The page will not edit these, because the next
/// restart would put them back.
/// </param>
public sealed record PersonDto(
    Guid Id,
    string Email,
    string DisplayName,
    string Role,
    bool IsActive,
    bool HasSignedIn,
    DateTimeOffset? LastLoginAt,
    DateTimeOffset CreatedAt,
    bool IsConfigAdmin);

public sealed record AddPersonRequest(string Email, string Role);

public sealed record SetRoleRequest(string Role);

/// <summary>
/// A page of the audit log, newest first.
/// </summary>
/// <param name="Names">
/// Display names for ids that appear inside entries' <c>Data</c>: games, teams
/// and scoring rules. The log stores ids, which stay correct when something is
/// renamed; this is what lets the page say "Baton Relay" instead of a GUID.
/// </param>
/// <param name="NextBefore">Pass back as <c>before</c> for the next page. Null at the end.</param>
public sealed record ActivityPageDto(
    IReadOnlyList<ActivityEntryDto> Entries,
    IReadOnlyDictionary<string, string> Names,
    DateTimeOffset? NextBefore);

/// <param name="ActorName">Null for anything the system did on its own.</param>
/// <param name="Session">The session the entry happened in, when there is one and it still exists.</param>
/// <param name="Data">
/// Whatever the action recorded, verbatim. Property names are PascalCase, the
/// way they were serialized when written.
/// </param>
public sealed record ActivityEntryDto(
    Guid Id,
    DateTimeOffset At,
    string Action,
    string EntityType,
    Guid EntityId,
    Guid? ActorId,
    string? ActorName,
    ActivitySessionDto? Session,
    System.Text.Json.JsonElement? Data);

public sealed record ActivitySessionDto(Guid Id, string DivisionName, DateOnly Date);
