namespace Awana.Data.Entities;

/// <summary>
/// One race, recorded. Four to eight of these make a session.
/// </summary>
public class Round
{
    public Guid Id { get; set; } = Guid.CreateVersion7();

    public Guid ChurchId { get; set; }
    public Church Church { get; set; } = null!;

    public Guid SessionId { get; set; }
    public Session Session { get; set; } = null!;

    /// <summary>
    /// Position within the session, from 1. Unique among rounds that are not
    /// voided, so voiding round 3 and recording a new one does not collide.
    /// </summary>
    public int RoundNumber { get; set; }

    public Guid GameId { get; set; }
    public Game Game { get; set; } = null!;

    /// <summary>
    /// Multiplies placement points for this round, for a final round or a
    /// tug-of-war worth double. Never multiplies bonuses.
    /// </summary>
    public decimal PointMultiplier { get; set; } = 1.0m;

    /// <summary>
    /// One value generated by the client per round ATTEMPT, unique within the
    /// session.
    ///
    /// This is what makes recording a round idempotent. On church wifi a POST
    /// can succeed and its response be lost; the retry carries the same value,
    /// and the server returns the existing round instead of scoring it twice.
    /// The v1 draft had nothing here.
    /// </summary>
    public Guid ClientRequestId { get; set; }

    public Guid? RecordedByUserId { get; set; }
    public AppUser? RecordedByUser { get; set; }

    public DateTimeOffset RecordedAt { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Rounds are voided, never deleted. The row stays so the night can be
    /// explained afterwards, and standings simply skip it.
    /// </summary>
    public DateTimeOffset? VoidedAt { get; set; }

    public Guid? VoidedByUserId { get; set; }
    public AppUser? VoidedByUser { get; set; }

    public string? VoidReason { get; set; }

    public ICollection<RoundResult> Results { get; set; } = [];
}
