// <auto-generated />
using System;
using System.Text.Json;
using Awana.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Awana.Data.Migrations
{
    [DbContext(typeof(AwanaDbContext))]
    [Migration("20260914064038_DropGameDivision")]
    partial class DropGameDivision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Awana.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid")
                        .HasColumnName("church_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleSubject")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("google_subject");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("GoogleSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_users_google_subject")
                        .HasFilter("google_subject IS NOT NULL");

                    b.HasIndex("ChurchId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_church_id_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Awana.Data.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid")
                        .HasColumnName("church_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_logs_actor_user_id");

                    b.HasIndex("ChurchId", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_church_id_created_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Awana.Data.Entities.Church", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id")
                        .HasName("pk_churches");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_churches_slug");

                    b.ToTable("churches", (string)null);
                });

            modelBuilder.Entity("Awana.Data.Entities.Division", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid")
                        .HasColumnName("church_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_divisions");

                    b.HasIndex("ChurchId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_divisions_church_id_slug");

                    b.ToTable("divisions", (string)null);
                });

            modelBuilder.Entity("Awana.Data.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid")
                        .HasColumnName("church_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("SeedKey")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("seed_key");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.HasIndex("ChurchId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_games_church_id_name");

                    b.HasIndex("ChurchId", "SeedKey")
                        .IsUnique()
                        .HasDatabaseName("ix_games_church_id_seed_key")
                        .HasFilter("seed_key IS NOT NULL");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("Awana.Data.Entities.PointAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid")
                        .HasColumnName("church_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<decimal>("Points")
                        .HasColumnType("numeric(9,3)")
                        .HasColumnName("points");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset?>("VoidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at");

                    b.Property<Guid?>("VoidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("voided_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_point_adjustments");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_point_adjustments_created_by_user_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_point_adjustments_session_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_point_adjustments_team_id");

                    b.HasIndex("VoidedByUserId")
                        .HasDatabaseName("ix_point_adjustments_voided_by_user_id");

                    b.HasIndex("ChurchId", "SessionId")
                        .HasDatabaseName("ix_point_adjustments_church_id_session_id");

                    b.ToTable("point_adjustments", (string)null);
                });

            modelBuilder.Entity("Awana.Data.Entities.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid")
                        .HasColumnName("church_id");

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_request_id");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<decimal>("PointMultiplier")
                        .HasColumnType("numeric(9,3)")
                        .HasColumnName("point_multiplier");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer")
                        .HasColumnName("round_number");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("void_reason");

                    b.Property<DateTimeOffset?>("VoidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at");

                    b.Property<Guid?>("VoidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("voided_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_rounds");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_rounds_game_id");

                    b.HasIndex("RecordedByUserId")
                        .HasDatabaseName("ix_rounds_recorded_by_user_id");

                    b.HasIndex("VoidedByUserId")
                        .HasDatabaseName("ix_rounds_voided_by_user_id");

                    b.HasIndex("ChurchId", "SessionId")
                        .HasDatabaseName("ix_rounds_church_id_session_id");

                    b.HasIndex("SessionId", "ClientRequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_rounds_session_id_client_request_id");

                    b.HasIndex("SessionId", "RoundNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_rounds_session_id_round_number")
                        .HasFilter("voided_at IS NULL");

                    b.ToTable("rounds", (string)null);
                });

            modelBuilder.Entity("Awana.Data.Entities.RoundResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BonusPoints")
                        .HasColumnType("numeric(9,3)")
                        .HasColumnName("bonus_points");

                    b.Property<string>("BonusReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bonus_reason");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("explanation");

                    b.Property<bool>("IsDisqualified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disqualified");

                    b.Property<int?>("Place")
                        .HasColumnType("integer")
                        .HasColumnName("place");

                    b.Property<decimal>("PointsAwarded")
                        .HasColumnType("numeric(9,3)")
                        .HasColumnName("points_awarded");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_round_results");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_round_results_team_id");

                    b.HasIndex("RoundId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("ix_round_results_round_id_team_id");

                    b.ToTable("round_results", (string)null);
                });

            modelBuilder.Entity("Awana.Data.Entities.ScoringProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid")
                        .HasColumnName("church_id");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_scoring_profiles");

                    b.HasIndex("ChurchId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_scoring_profiles_church_id_name");

                    b.ToTable("scoring_profiles", (string)null);
                });

            modelBuilder.Entity("Awana.Data.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid")
                        .HasColumnName("church_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("division_id");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("PublicSlug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("public_slug");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("ScoringConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("scoring_config_json");

                    b.Property<int>("ScoringConfigSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("scoring_config_schema_version");

                    b.Property<Guid?>("ScoringProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("scoring_profile_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_sessions_created_by_user_id");

                    b.HasIndex("DivisionId")
                        .HasDatabaseName("ix_sessions_division_id");

                    b.HasIndex("PublicSlug")
                        .IsUnique()
                        .HasDatabaseName("ix_sessions_public_slug");

                    b.HasIndex("ScoringProfileId")
                        .HasDatabaseName("ix_sessions_scoring_profile_id");

                    b.HasIndex("ChurchId", "Status")
                        .HasDatabaseName("ix_sessions_church_id_status");

                    b.HasIndex("ChurchId", "DivisionId", "Date")
                        .HasDatabaseName("ix_sessions_church_id_division_id_date");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Awana.Data.Entities.SessionTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Headcount")
                        .HasColumnType("integer")
                        .HasColumnName("headcount");

                    b.Property<DateTimeOffset?>("HeadcountRecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("headcount_recorded_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_session_teams");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_session_teams_team_id");

                    b.HasIndex("SessionId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("ix_session_teams_session_id_team_id");

                    b.ToTable("session_teams", (string)null);
                });

            modelBuilder.Entity("Awana.Data.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid")
                        .HasColumnName("church_id");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color_hex");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("division_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TextOnColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("text_on_color_hex");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("DivisionId")
                        .HasDatabaseName("ix_teams_division_id");

                    b.HasIndex("ChurchId", "DivisionId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_church_id_division_id_name");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Awana.Data.Entities.AppUser", b =>
                {
                    b.HasOne("Awana.Data.Entities.Church", "Church")
                        .WithMany("Users")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_churches_church_id");

                    b.Navigation("Church");
                });

            modelBuilder.Entity("Awana.Data.Entities.AuditLog", b =>
                {
                    b.HasOne("Awana.Data.Entities.AppUser", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_logs_users_actor_user_id");

                    b.HasOne("Awana.Data.Entities.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_churches_church_id");

                    b.Navigation("ActorUser");

                    b.Navigation("Church");
                });

            modelBuilder.Entity("Awana.Data.Entities.Division", b =>
                {
                    b.HasOne("Awana.Data.Entities.Church", "Church")
                        .WithMany("Divisions")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_divisions_churches_church_id");

                    b.Navigation("Church");
                });

            modelBuilder.Entity("Awana.Data.Entities.Game", b =>
                {
                    b.HasOne("Awana.Data.Entities.Church", "Church")
                        .WithMany("Games")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_games_churches_church_id");

                    b.Navigation("Church");
                });

            modelBuilder.Entity("Awana.Data.Entities.PointAdjustment", b =>
                {
                    b.HasOne("Awana.Data.Entities.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_point_adjustments_churches_church_id");

                    b.HasOne("Awana.Data.Entities.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_point_adjustments_users_created_by_user_id");

                    b.HasOne("Awana.Data.Entities.Session", "Session")
                        .WithMany("PointAdjustments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_point_adjustments_sessions_session_id");

                    b.HasOne("Awana.Data.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_point_adjustments_teams_team_id");

                    b.HasOne("Awana.Data.Entities.AppUser", "VoidedByUser")
                        .WithMany()
                        .HasForeignKey("VoidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_point_adjustments_users_voided_by_user_id");

                    b.Navigation("Church");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Session");

                    b.Navigation("Team");

                    b.Navigation("VoidedByUser");
                });

            modelBuilder.Entity("Awana.Data.Entities.Round", b =>
                {
                    b.HasOne("Awana.Data.Entities.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rounds_churches_church_id");

                    b.HasOne("Awana.Data.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rounds_games_game_id");

                    b.HasOne("Awana.Data.Entities.AppUser", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_rounds_users_recorded_by_user_id");

                    b.HasOne("Awana.Data.Entities.Session", "Session")
                        .WithMany("Rounds")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rounds_sessions_session_id");

                    b.HasOne("Awana.Data.Entities.AppUser", "VoidedByUser")
                        .WithMany()
                        .HasForeignKey("VoidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_rounds_users_voided_by_user_id");

                    b.Navigation("Church");

                    b.Navigation("Game");

                    b.Navigation("RecordedByUser");

                    b.Navigation("Session");

                    b.Navigation("VoidedByUser");
                });

            modelBuilder.Entity("Awana.Data.Entities.RoundResult", b =>
                {
                    b.HasOne("Awana.Data.Entities.Round", "Round")
                        .WithMany("Results")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_round_results_rounds_round_id");

                    b.HasOne("Awana.Data.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_round_results_teams_team_id");

                    b.Navigation("Round");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Awana.Data.Entities.ScoringProfile", b =>
                {
                    b.HasOne("Awana.Data.Entities.Church", "Church")
                        .WithMany("ScoringProfiles")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_scoring_profiles_churches_church_id");

                    b.Navigation("Church");
                });

            modelBuilder.Entity("Awana.Data.Entities.Session", b =>
                {
                    b.HasOne("Awana.Data.Entities.Church", "Church")
                        .WithMany("Sessions")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_churches_church_id");

                    b.HasOne("Awana.Data.Entities.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sessions_users_created_by_user_id");

                    b.HasOne("Awana.Data.Entities.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_divisions_division_id");

                    b.HasOne("Awana.Data.Entities.ScoringProfile", "ScoringProfile")
                        .WithMany()
                        .HasForeignKey("ScoringProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sessions_scoring_profiles_scoring_profile_id");

                    b.Navigation("Church");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Division");

                    b.Navigation("ScoringProfile");
                });

            modelBuilder.Entity("Awana.Data.Entities.SessionTeam", b =>
                {
                    b.HasOne("Awana.Data.Entities.Session", "Session")
                        .WithMany("SessionTeams")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_teams_sessions_session_id");

                    b.HasOne("Awana.Data.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_teams_teams_team_id");

                    b.Navigation("Session");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Awana.Data.Entities.Team", b =>
                {
                    b.HasOne("Awana.Data.Entities.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teams_churches_church_id");

                    b.HasOne("Awana.Data.Entities.Division", "Division")
                        .WithMany("Teams")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teams_divisions_division_id");

                    b.Navigation("Church");

                    b.Navigation("Division");
                });

            modelBuilder.Entity("Awana.Data.Entities.Church", b =>
                {
                    b.Navigation("Divisions");

                    b.Navigation("Games");

                    b.Navigation("ScoringProfiles");

                    b.Navigation("Sessions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Awana.Data.Entities.Division", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Awana.Data.Entities.Round", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("Awana.Data.Entities.Session", b =>
                {
                    b.Navigation("PointAdjustments");

                    b.Navigation("Rounds");

                    b.Navigation("SessionTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
